services:

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8080"
    networks:
      - library-net

  book-service:
    build: ./book-service
    container_name: book-service
    ports:
      - "8082:8080"
    networks:
      - library-net

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8084:8080"
    networks:
      - library-net

  borrow-service:
    build: ./borrow-service
    container_name: borrow-service
    ports:
      - "8083:8080"
    depends_on:
      - book-service
      - notification-service
    networks:
      - library-net
    environment:
      - BOOK_SERVICE_URL=http://book-service:8080
      - NOTIFICATION_SERVICE_URL=http://notification-service:8080

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8085:80"
    depends_on:
      - user-service
      - book-service
      - borrow-service
    networks:
      - library-net

networks:
  library-net:
    driver: bridge
