server.port=8080
spring.datasource.url=jdbc:h2:mem:borrowdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
book.service.url=${BOOK_SERVICE_URL:http://book-service}
notification.service.url=${NOTIFICATION_SERVICE_URL:http://notification-service}
